apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: default
  labels:
    app: demo-app
spec:
  type: LoadBalancer   # creates an AWS ELB in public subnets
  selector:
    app: demo-app
  ports:
    - name: http
      port: 80
      targetPort: 80

